In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv("calibrationtry2.csv", header = 0)

In [3]:
df.columns.values

array(['index', 'phbox', 'phprobe', '415nm', '445nm', '480nm', '515nm',
       '555nm', '590nm', '630nm', '680nm'], dtype=object)

In [4]:
df.shape

(81, 11)

In [5]:
df.iloc[0]

index        83.00
phbox         1.30
phprobe       4.53
415nm       128.00
445nm       827.90
480nm       703.00
515nm      1022.40
555nm      1266.60
590nm      1310.50
630nm      1428.50
680nm       738.80
Name: 0, dtype: float64

In [6]:
X = df.drop(columns=['index', 'phbox', 'phprobe']).to_numpy()
y = df['phprobe'].to_numpy()

In [7]:
X

array([[ 128. ,  827.9,  703. , 1022.4, 1266.6, 1310.5, 1428.5,  738.8],
       [ 139.2,  855.1,  785. , 1203.4, 1444.4, 1375.5, 1490.3,  769.5],
       [  94. ,  629. ,  571.8,  891.9,  966.2,  832.4,  935.9,  557.6],
       [ 126. ,  765.7,  692.9, 1011.6, 1254.4, 1279. , 1396.4,  720.2],
       [  96.9,  710.9,  609.9,  884. ,  938.8,  803.9,  931. ,  573.8],
       [ 126. ,  826.4,  681.9,  980.9, 1217.9, 1279.2, 1399. ,  724. ],
       [ 129. ,  932.4,  786.4, 1111.4, 1167.3, 1036.3, 1207.3,  728.2],
       [ 122. ,  793.7,  654.2,  934. , 1182.3, 1267.5, 1392.1,  717.4],
       [ 127. ,  887.9,  772. , 1059.6, 1123.8, 1019.8, 1198.6,  726.6],
       [ 128.9,  885.3,  684.1,  980.9, 1225.6, 1315. , 1427.3,  740. ],
       [ 120.7,  946.1,  728.5,  984.7, 1022.3,  959.5, 1115.9,  696.8],
       [ 126.9,  793.8,  676.2,  953. , 1222. , 1304. , 1432.3,  738.5],
       [ 123. ,  881.8,  743.2,  998.8, 1061.3, 1003.2, 1182.2,  727. ],
       [ 122.8,  796.1,  639.7,  911.8, 1179.2, 128

In [8]:
y

array([ 4.53,  4.16,  6.97,  3.97,  8.13,  3.8 ,  8.51,  3.66,  8.76,
        3.4 ,  8.87,  3.2 ,  9.15,  3.04,  9.3 ,  2.84,  9.56,  2.66,
        9.78,  2.41, 10.07,  2.17, 10.23,  2.02, 10.62,  1.87, 10.96,
       11.21,  4.25,  4.87,  3.81,  5.17,  3.79,  5.41,  3.76,  5.71,
        3.65,  5.89,  3.49,  5.93,  3.22,  6.18,  2.97,  6.35,  2.71,
        7.22,  2.22,  7.2 ,  1.96,  6.7 ,  7.2 ,  3.66,  7.44,  3.91,
        8.07,  4.  ,  4.11,  8.27,  4.27,  8.43,  4.51,  8.54,  5.02,
        8.74,  5.68,  8.92,  6.25,  9.14,  9.06,  9.43,  7.25,  9.63,
        6.37,  9.78,  4.98,  9.98,  4.76, 10.22,  4.39, 10.53, 10.85])

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=5)

In [10]:
reg = LinearRegression().fit(X_train, y_train)

In [11]:
y_test

array([ 4.51, 10.96,  8.87,  5.71, 10.07,  1.96,  9.06, 10.62,  2.66,
        3.66,  9.15,  4.  ,  4.76,  3.76,  3.04,  6.35,  7.44, 10.23,
        9.63,  8.51, 10.53])

In [12]:
reg.predict(X_test)

array([ 3.89884812,  9.41180125,  9.35305112,  5.53418591,  9.30442281,
        2.59920744,  9.48199325,  9.37091232,  2.99582281,  3.84193697,
       10.02042661,  3.79620325,  4.17632552,  4.1303698 ,  3.14319329,
        6.52177651,  7.94452837,  9.60295752,  9.53878826,  9.38776008,
        9.15153637])

In [13]:
reg.score(X_test, y_test)

0.9434297313450202

In [14]:
reg.coef_

array([-0.29185504, -0.00273654,  0.04974995,  0.00562701, -0.01471374,
       -0.00918647,  0.01269146,  0.01608802])

In [15]:
reg.intercept_

3.868977986033828

In [22]:
np.average(np.subtract(reg.predict(X_test), y_test))

-0.1082834480352467

In [17]:
y_test

array([ 4.51, 10.96,  8.87,  5.71, 10.07,  1.96,  9.06, 10.62,  2.66,
        3.66,  9.15,  4.  ,  4.76,  3.76,  3.04,  6.35,  7.44, 10.23,
        9.63,  8.51, 10.53])

In [25]:
np.std(np.subtract(reg.predict(X_test), y_test))

0.7007197413616529